# Generated by Django 4.1.4 on 2023-01-01 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webdulich', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
