# Generated by Django 4.1.4 on 2023-01-01 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('webdulich', '0002_delete_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('slug', models.SlugField(blank=True, max_length=254, unique=True)),
                ('author_name', models.CharField(max_length=35)),
                ('short_description', models.TextField(verbose_name='Short description')),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('publish_at', models.DateTimeField(verbose_name='Publish at')),
                ('feature_img', models.ImageField(blank=True, max_length=254, null=True, upload_to='img/2023/1', verbose_name='Feature Image')),
                ('status', models.BooleanField(default=0, verbose_name='Status')),
                ('views_count', models.IntegerField(default=0, verbose_name='Views count')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Post',
                'ordering': ['-publish_at'],
                'get_latest_by': 'created_at',
            },
        ),
    ]
