# Generated by Django 4.1.4 on 2023-01-02 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webdulich', '0004_alter_post_feature_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_code',
            field=models.IntegerField(default=0, verbose_name='Post code'),
        ),
    ]
