# Generated by Django 4.1.4 on 2023-01-04 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webdulich', '0006_alter_post_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_code',
        ),
    ]
