# Generated by Django 4.1.4 on 2023-01-04 17:40

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webdulich', '0010_discover'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('slug', models.SlugField(blank=True, max_length=254, unique=True)),
                ('author_name', models.CharField(max_length=35)),
                ('short_description', models.TextField(verbose_name='Short description')),
                ('description', ckeditor.fields.RichTextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('publish_at', models.DateTimeField(verbose_name='Publish at')),
                ('feature_img', models.ImageField(blank=True, max_length=254, null=True, upload_to='media', verbose_name='Feature Image')),
                ('status', models.BooleanField(default=0, verbose_name='Status')),
                ('views_count', models.IntegerField(default=0, verbose_name='Views count')),
            ],
            options={
                'verbose_name': 'Food',
                'verbose_name_plural': 'Food',
                'ordering': ['-publish_at'],
                'get_latest_by': 'created_at',
            },
        ),
    ]
